-- PHARMACIES COMBINED TABLE CREATION
-- Creates a unified pharmacies table from eight source tables.
-- Municipality and city columns are left NULL pending geocoding verification.
-- Source: MUSA_DAIR_DB.RAW schema tables from medical aid provider networks.


-- TABLE CREATION
-- Drops existing table if present and creates new table schema.
DROP TABLE IF EXISTS MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED;

CREATE TABLE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED (
    PROVINCE VARCHAR,
    LOCAL_MUNICIPALITY VARCHAR,
    DISTRICT_MUNICIPALITY VARCHAR,
    METROPOLITAN_MUNICIPALITY VARCHAR,
    CITY VARCHAR,
    PRACTICE_NAME VARCHAR,
    PRACTICE_NUM VARCHAR,
    PRACTICE_TYPE VARCHAR,
    ADDRESS VARCHAR,
    PHONE VARCHAR,
    FUNDING VARCHAR,
    COMPANY VARCHAR,
    COORDS GEOGRAPHY
);


-- SOURCE 1: GEMS GAUTENG
-- Original columns: PROVINCE, CITY, SUBURB, ADDRESS, PRACTICE_NAME, PRACTICE_NUM, PHONE.
-- Contains clean data with proper structure.
-- CITY and SUBURB are concatenated into ADDRESS for geocoding context.
INSERT INTO MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
    (PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY, 
     PRACTICE_NAME, PRACTICE_NUM, PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS)
SELECT 
    'Gauteng' AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    NULL AS DISTRICT_MUNICIPALITY,
    NULL AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    TRIM(PRACTICE_NUM) AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(
        CONCAT_WS(', ',
            NULLIF(TRIM(ADDRESS), ''),
            NULLIF(TRIM(SUBURB), ''),
            NULLIF(TRIM(CITY), '')
        )
    )) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'GEMS' AS COMPANY,
    NULL AS COORDS
FROM MUSA_DAIR_DB.RAW.PHARMACIES_GEMS_GAUTENG
WHERE PRACTICE_NAME IS NOT NULL 
  AND TRIM(PRACTICE_NAME) != '';


-- SOURCE 2: GEMS KZN
-- Original columns: PROVINCE, CITY, SUBURB, ADDRESS, PRACTICE_NAME, PRACTICE_NUM, PHONE.
-- Contains clean data with proper structure.
-- CITY and SUBURB are concatenated into ADDRESS for geocoding context.
INSERT INTO MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
    (PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY, 
     PRACTICE_NAME, PRACTICE_NUM, PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS)
SELECT 
    'Kwazulu-Natal' AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    NULL AS DISTRICT_MUNICIPALITY,
    NULL AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    TRIM(PRACTICE_NUM) AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(
        CONCAT_WS(', ',
            NULLIF(TRIM(ADDRESS), ''),
            NULLIF(TRIM(SUBURB), ''),
            NULLIF(TRIM(CITY), '')
        )
    )) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'GEMS' AS COMPANY,
    NULL AS COORDS
FROM MUSA_DAIR_DB.RAW.PHARMACIES_GEMS_KZN
WHERE PRACTICE_NAME IS NOT NULL 
  AND TRIM(PRACTICE_NAME) != '';


-- SOURCE 3: MOMENTUM GAUTENG
-- Original columns: PRACTICE_NAME, ADDRESS, STREET, AREA, POSTAL, PHONE, FAX.
-- ADDRESS contains building/shop info.
-- STREET contains street address.
-- AREA contains suburb.
-- Combining ADDRESS + STREET + AREA + POSTAL for complete geocodable address.
INSERT INTO MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
    (PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY, 
     PRACTICE_NAME, PRACTICE_NUM, PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS)
SELECT 
    'Gauteng' AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    NULL AS DISTRICT_MUNICIPALITY,
    NULL AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    NULL AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(
        CONCAT_WS(', ',
            NULLIF(TRIM(ADDRESS), ''),
            NULLIF(TRIM(STREET), ''),
            NULLIF(TRIM(AREA), ''),
            NULLIF(TRIM(POSTAL), '')
        )
    )) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'Momentum' AS COMPANY,
    NULL AS COORDS
FROM MUSA_DAIR_DB.RAW.PHARMACIES_MOMENTUM_GAUTENG
WHERE PRACTICE_NAME IS NOT NULL 
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) != 'PRACTICE_NAME';


-- SOURCE 4: MOMENTUM KZN
-- Original columns: PRACTICE_NAME, ADDRESS, STREET, AREA, POSTAL, PHONE, FAX.
-- ADDRESS contains building/shop info.
-- STREET contains street address.
-- AREA contains suburb.
-- Combining ADDRESS + STREET + AREA + POSTAL for complete geocodable address.
INSERT INTO MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
    (PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY, 
     PRACTICE_NAME, PRACTICE_NUM, PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS)
SELECT 
    'Kwazulu-Natal' AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    NULL AS DISTRICT_MUNICIPALITY,
    NULL AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    NULL AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(
        CONCAT_WS(', ',
            NULLIF(TRIM(ADDRESS), ''),
            NULLIF(TRIM(STREET), ''),
            NULLIF(TRIM(AREA), ''),
            NULLIF(TRIM(POSTAL), '')
        )
    )) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'Momentum' AS COMPANY,
    NULL AS COORDS
FROM MUSA_DAIR_DB.RAW.PHARMACIES_MOMENTUM_KZN
WHERE PRACTICE_NAME IS NOT NULL 
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) != 'PRACTICE_NAME';


-- SOURCE 5: WOOLTRU GAUTENG
-- Original columns: PRACTICE_NUM, PRACTICE_NAME, ADDRESS, CITY, PHONE.
-- CITY column often contains suburb or address fragments.
-- Appending CITY to ADDRESS for better geocoding results.
INSERT INTO MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
    (PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY, 
     PRACTICE_NAME, PRACTICE_NUM, PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS)
SELECT 
    'Gauteng' AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    NULL AS DISTRICT_MUNICIPALITY,
    NULL AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    TRIM(PRACTICE_NUM) AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(
        CONCAT_WS(', ',
            NULLIF(TRIM(ADDRESS), ''),
            NULLIF(TRIM(CITY), '')
        )
    )) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'Wooltru' AS COMPANY,
    NULL AS COORDS
FROM MUSA_DAIR_DB.RAW.PHARMACIES_WOOLTRU_GAUTENG
WHERE PRACTICE_NAME IS NOT NULL 
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) NOT IN ('PRACTICE_NAME', 'PRACTICE NAME');


-- SOURCE 6: WOOLTRU KZN
-- Original columns: PRACTICE_NUM, PRACTICE_NAME, ADDRESS, CITY, PHONE.
-- CITY column often contains suburb or address fragments.
-- Appending CITY to ADDRESS for better geocoding results.
INSERT INTO MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
    (PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY, 
     PRACTICE_NAME, PRACTICE_NUM, PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS)
SELECT 
    'Kwazulu-Natal' AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    NULL AS DISTRICT_MUNICIPALITY,
    NULL AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    TRIM(PRACTICE_NUM) AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(
        CONCAT_WS(', ',
            NULLIF(TRIM(ADDRESS), ''),
            NULLIF(TRIM(CITY), '')
        )
    )) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'Wooltru' AS COMPANY,
    NULL AS COORDS
FROM MUSA_DAIR_DB.RAW.PHARMACIES_WOOLTRU_KZN
WHERE PRACTICE_NAME IS NOT NULL 
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) NOT IN ('PRACTICE_NAME', 'PRACTICE NAME');


-- SOURCE 7: SAMWUMED
-- Original columns: PRACTICE_NUM, PRACTICE_NAME, PHONE, EMAIL, ADDRESS, SUBURB, CITY.
-- Province must be inferred from CITY values since no PROVINCE column exists.
-- Filtering to only Gauteng and KZN cities based on known city lists.
-- Combining ADDRESS + SUBURB + CITY for geocoding.
INSERT INTO MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
    (PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY, 
     PRACTICE_NAME, PRACTICE_NUM, PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS)
SELECT 
    CASE 
        WHEN UPPER(TRIM(CITY)) IN (
            'JOHANNESBURG', 'JOHANNESBURG SOUTH', 'JOHANNESBURG CBD',
            'SANDTON', 'RANDBURG', 'ROODEPOORT', 'SOWETO',
            'CENTURION', 'PRETORIA', 'PRETORIA NORTH', 'PRETORIA WEST', 'PRETORIA EAST',
            'MIDRAND', 'KEMPTON PARK', 'BENONI', 'BOKSBURG',
            'GERMISTON', 'ALBERTON', 'SPRINGS', 'BRAKPAN',
            'EDENVALE', 'KRUGERSDORP', 'RANDFONTEIN', 'CARLETONVILLE',
            'VEREENIGING', 'VANDERBIJLPARK', 'HEIDELBERG', 'HEIDELBERG - GP',
            'NIGEL', 'BRONKHORSTSPRUIT', 'CULLINAN',
            'AKASIA', 'LENASIA', 'LENASIA SOUTH',
            'TEMBISA', 'KATLEHONG', 'DAVEYTON',
            'GA-RANKUWA', 'SOSHANGUVE', 'MABOPANE',
            'MAMELODI', 'ATTERIDGEVILLE', 'DIEPSLOOT', 'ALEXANDRA',
            'COSMO CITY', 'FOURWAYS', 'BRYANSTON',
            'BEDFORDVIEW', 'PRIMROSE',
            'HONEYDEW', 'FLORIDA',
            'WESTONARIA', 'FOCHVILLE', 'MEYERTON',
            'SEBOKENG', 'EVATON', 'ORANGE FARM',
            'VOSLOORUS', 'KAGISO', 'DOBSONVILLE',
            'MEADOWLANDS', 'DIEPKLOOF',
            'ELDORADOPARK', 'ENNERDALE',
            'MULBARTON', 'GLENVISTA', 'MONDEOR',
            'ROSETTENVILLE', 'TURFFONTEIN',
            'NORTHRIDING', 'NORTH RIDING', 'FERNDALE', 'NORTHCLIFF',
            'LINDEN', 'EMMARENTIA',
            'MORNINGSIDE', 'RIVONIA',
            'HALFWAY HOUSE', 'GLEN MARAIS',
            'GREENSTONE HILL',
            'BIRCHLEIGH',
            'IVORY PARK',
            'CLUBVIEW', 'WIERDAPARK',
            'LAUDIUM', 'WATERKLOOF',
            'HATFIELD', 'ARCADIA', 'SUNNYSIDE', 'GEZINA',
            'MONTANA', 'SINOVILLE', 'WONDERBOOM',
            'LYNNWOOD', 'MENLYN',
            'MORELETA PARK',
            'NORTHGATE',
            'MAGALIESBURG', 'HAMMANSKRAAL'
        ) THEN 'Gauteng'
        WHEN UPPER(TRIM(CITY)) IN (
            'DURBAN', 'DURBAN NORTH', 'DURBAN CENTRAL',
            'PIETERMARITZBURG',
            'NEWCASTLE', 'RICHARDS BAY',
            'PINETOWN', 'PHOENIX', 'CHATSWORTH',
            'AMANZIMTOTI', 'UMHLANGA',
            'BALLITO',
            'EMPANGENI', 'LADYSMITH', 'VRYHEID',
            'PORT SHEPSTONE', 'SHELLY BEACH', 'MARGATE', 'SOUTHBROOM', 'UVONGO',
            'SCOTTBURGH', 'PENNINGTON',
            'STANGER', 'KWADUKUZA',
            'TONGAAT', 'VERULAM', 'WESTVILLE',
            'KLOOF', 'HILLCREST', 'HOWICK',
            'ESTCOURT', 'DUNDEE', 'ESHOWE',
            'MTUBATUBA', 'KOKSTAD', 'GREYTOWN',
            'UMLAZI', 'KWAMASHU',
            'INANDA', 'ISIPINGO',
            'QUEENSBURGH', 'BLUFF', 'OVERPORT',
            'MUSGRAVE', 'SHALLCROSS',
            'MALVERN', 'MOUNT EDGECOMBE',
            'PONGOLA', 'JOZINI', 'HLUHLUWE',
            'NONGOMA', 'ULUNDI',
            'BERGVILLE', 'WINTERTON', 'MOOI RIVER',
            'GLENCOE', 'DANNHAUSER', 'MELMOTH',
            'NKANDLA', 'TUGELA FERRY', 'KRANSKOP', 'WARTBURG',
            'HAMMARSDALE', 'MPUMALANGA', 'UMZINTO',
            'UMKOMAAS', 'KINGSBURGH',
            'UMBILO', 'GLENWOOD', 'BEREA',
            'SYDENHAM',
            'LA LUCIA',
            'SHAKASKRAAL', 'SALT ROCK',
            'MTUNZINI', 'MANDENI',
            'NTUZUMA',
            'MEREBANK', 'WENTWORTH',
            'RESERVOIR HILLS',
            'SCOTTSVILLE',
            'HILTON', 'MPOPHOMENI',
            'EDENDALE', 'NORTHDALE',
            'IMBALI',
            'PAULPIETERSBURG',
            'MADADENI', 'OSIZWENI',
            'EZAKHENI',
            'NGWELEZANE',
            'ST LUCIA',
            'GINGINDLOVU',
            'PARK RYNIE', 'HIBBERDENE',
            'HARDING', 'UMZIMKHULU'
        ) THEN 'Kwazulu-Natal'
        ELSE NULL
    END AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    NULL AS DISTRICT_MUNICIPALITY,
    NULL AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    TRIM(PRACTICE_NUM) AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(
        CONCAT_WS(', ',
            NULLIF(TRIM(ADDRESS), ''),
            NULLIF(TRIM(SUBURB), ''),
            NULLIF(TRIM(CITY), '')
        )
    )) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'SAMWUMED' AS COMPANY,
    NULL AS COORDS
FROM MUSA_DAIR_DB.RAW.PHARMACIES_SAMWUMED
WHERE PRACTICE_NAME IS NOT NULL 
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) NOT IN ('PRACTICE_NAME', 'PRACTICE NAME')
  AND UPPER(TRIM(CITY)) NOT LIKE '%SHOP%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%CENTRE%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%MALL%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%ROAD%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%STREET%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%AVENUE%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%CNR%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%BUILDING%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%FLOOR%'
  AND CITY IS NOT NULL
  AND TRIM(CITY) != '';


-- SOURCE 8: VITALITY WELLNESS
-- Original columns: PROVINCE, PRACTICE_TYPE, PRACTICE_NAME, ADDRESS, SUBURB, CITY, PHONE.
-- CITY column contains suburb-level data.
-- SUBURB column contains address fragments.
-- Combining ADDRESS + SUBURB + CITY for complete geocodable address.
-- Filtering to only Gauteng and KZN provinces.
-- Filtering to only Pharmacy practice types.
INSERT INTO MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
    (PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY, 
     PRACTICE_NAME, PRACTICE_NUM, PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS)
SELECT 
    CASE 
        WHEN UPPER(TRIM(PROVINCE)) LIKE '%GAUTENG%' THEN 'Gauteng'
        WHEN UPPER(TRIM(PROVINCE)) LIKE '%KWAZULU%' THEN 'Kwazulu-Natal'
        WHEN UPPER(TRIM(PROVINCE)) LIKE '%KZN%' THEN 'Kwazulu-Natal'
        ELSE NULL
    END AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    NULL AS DISTRICT_MUNICIPALITY,
    NULL AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    NULL AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(
        CONCAT_WS(', ',
            NULLIF(TRIM(ADDRESS), ''),
            NULLIF(TRIM(SUBURB), ''),
            NULLIF(TRIM(CITY), '')
        )
    )) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'Vitality' AS COMPANY,
    NULL AS COORDS
FROM MUSA_DAIR_DB.RAW.PHARMACIES_VITALITY_WELLNESS
WHERE PRACTICE_NAME IS NOT NULL 
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) NOT IN ('PRACTICE_NAME', 'PRACTICE NAME')
  AND UPPER(TRIM(PRACTICE_TYPE)) LIKE '%PHARM%'
  AND (
      UPPER(TRIM(PROVINCE)) LIKE '%GAUTENG%'
      OR UPPER(TRIM(PROVINCE)) LIKE '%KWAZULU%'
      OR UPPER(TRIM(PROVINCE)) LIKE '%KZN%'
  );


-- REMOVE NULL PROVINCE RECORDS (OPTIONAL)
-- Removes records where province could not be determined from SAMWUMED inference.
-- DELETE FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
-- WHERE PROVINCE IS NULL;


-- STANDARDIZE PROVINCE NAMES
-- Ensures consistent naming convention across all records.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PROVINCE = 'Gauteng'
WHERE UPPER(REPLACE(REPLACE(TRIM(PROVINCE), '-', ''), ' ', '')) = 'GAUTENG';

UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PROVINCE = 'Kwazulu-Natal'
WHERE UPPER(REPLACE(REPLACE(TRIM(PROVINCE), '-', ''), ' ', '')) IN ('KZN', 'KWAZULUNATAL');


-- STANDARDIZE PRACTICE TYPE
-- Normalizes practice type values to consistent format.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PRACTICE_TYPE = 'Pharmacy'
WHERE UPPER(PRACTICE_TYPE) IN ('PHARMACIES', 'PHARMACY', 'PHARM');


-- CLEAN PHONE NUMBERS STEP 1
-- Removes all non-numeric characters from phone numbers.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PHONE = REGEXP_REPLACE(PHONE, '[^0-9]', '')
WHERE PHONE IS NOT NULL;


-- CLEAN PHONE NUMBERS STEP 2
-- Handles phone numbers with multiple numbers separated by slashes by taking first number.
-- Removes leading zeros if number is 11+ digits due to international format artifact.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PHONE = LEFT(PHONE, 10)
WHERE PHONE IS NOT NULL 
  AND LENGTH(PHONE) > 10;


-- CLEAN PHONE NUMBERS STEP 3
-- Sets invalid phone numbers to NULL when not 10 digits after cleaning.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PHONE = NULL
WHERE PHONE IS NOT NULL 
  AND LENGTH(PHONE) != 10;


-- CLEAN ADDRESS STEP 1
-- Removes double commas and normalizes comma spacing.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = REGEXP_REPLACE(ADDRESS, ',\\s*,', ',')
WHERE ADDRESS IS NOT NULL;


-- CLEAN ADDRESS STEP 2
-- Removes leading and trailing commas from address strings.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = TRIM(TRIM(ADDRESS), ',')
WHERE ADDRESS IS NOT NULL;


-- CLEAN ADDRESS STEP 3
-- Normalizes multiple spaces to single space.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = REGEXP_REPLACE(ADDRESS, '\\s+', ' ')
WHERE ADDRESS IS NOT NULL;


-- CLEAN ADDRESS STEP 4
-- Removes leading periods and normalizes period spacing.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = TRIM(TRIM(ADDRESS), '.')
WHERE ADDRESS IS NOT NULL;


-- CLEAN ADDRESS STEP 5
-- Ensures consistent comma spacing with space after comma but not before.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = REGEXP_REPLACE(ADDRESS, '\\s*,\\s*', ', ')
WHERE ADDRESS IS NOT NULL;


-- CLEAN ADDRESS STEP 6
-- Performs final trim of addresses.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = TRIM(ADDRESS)
WHERE ADDRESS IS NOT NULL;


-- REMOVE EMPTY ADDRESS RECORDS (OPTIONAL)
-- Removes records with no usable address for geocoding.
-- DELETE FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
-- WHERE ADDRESS IS NULL 
--   OR TRIM(ADDRESS) = ''
--   OR TRIM(ADDRESS) = ',';


-- CONSERVATIVE DEDUPLICATION USING PRACTICE_NUM
-- Deduplicates records WITH PRACTICE_NUM based on PRACTICE_NUM + COMPANY combination.
-- Keeps ALL records with NULL PRACTICE_NUM for spatial deduplication post-geocoding.
-- When duplicates exist, keeps record with longest ADDRESS as most complete for geocoding.
CREATE OR REPLACE TABLE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY PROVINCE, PRACTICE_NAME, COMPANY) AS PHARMACY_ID,
    PROVINCE,
    LOCAL_MUNICIPALITY,
    DISTRICT_MUNICIPALITY,
    METROPOLITAN_MUNICIPALITY,
    CITY,
    PRACTICE_NAME,
    PRACTICE_NUM,
    PRACTICE_TYPE,
    ADDRESS,
    PHONE,
    FUNDING,
    COMPANY,
    COORDS
FROM (
    SELECT 
        *,
        CASE 
            WHEN PRACTICE_NUM IS NOT NULL THEN
                ROW_NUMBER() OVER (
                    PARTITION BY PRACTICE_NUM, COMPANY 
                    ORDER BY LENGTH(ADDRESS) DESC, PRACTICE_NAME
                )
            ELSE 1
        END AS row_num
    FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
)
WHERE row_num = 1;


-- EMPTY ROWS REMOVAL
-- Drops rows where both address and practice number are null.
DELETE FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
WHERE ADDRESS IS NULL 
AND PRACTICE_NUM IS NULL;


-- VALIDATION COUNTS
-- Output record counts by province and company source for verification.
SELECT 'RECORD COUNTS BY PROVINCE' AS VALIDATION;
SELECT PROVINCE, COUNT(*) AS RECORD_COUNT 
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
GROUP BY PROVINCE;

SELECT 'RECORD COUNTS BY COMPANY SOURCE' AS VALIDATION;
SELECT COMPANY, COUNT(*) AS RECORD_COUNT 
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
GROUP BY COMPANY 
ORDER BY RECORD_COUNT DESC;

SELECT 'RECORDS WITH PRACTICE_NUM VS NULL' AS VALIDATION;
SELECT 
    CASE WHEN PRACTICE_NUM IS NOT NULL THEN 'Has PRACTICE_NUM' ELSE 'NULL PRACTICE_NUM' END AS PRACTICE_NUM_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY PRACTICE_NUM_STATUS;

SELECT 'TOTAL RECORD COUNT' AS VALIDATION;
SELECT COUNT(*) AS TOTAL_RECORDS 
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED;

SELECT 'SAMPLE RECORDS' AS VALIDATION;
SELECT * 
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
LIMIT 20;
