-- PROVINCE POPULATION AND GAUTENG/KZN FILTERING
-- Populates missing PROVINCE values using PROVINCE_LOOKUP, then drops non-GP/KZN records.
-- Source Tables:
--   MUSA_DAIR_DB.RAW.PROVINCE_LOOKUP (geographic lookup with GP and KZN cities).
--   MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED (pharmacy records, some missing PROVINCE).
-- Final Output: Pharmacies table containing only Gauteng and KwaZulu-Natal records.


-- MANUAL DATA CORRECTIONS
-- Corrects specific records with known data issues.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PHONE = '0214888270'
WHERE PRACTICE_NUM = '1253085';

UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = 'Shop 1, John Montague Centre, 19 Montague Dr, Montague Gardens, Cape Town, Western Cape, 7441.0, South Africa'
WHERE PRACTICE_NUM = '1253085';

UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = 'Osborne Rd, Eshowe, KwaZulu-Natal, 3815'
WHERE PRACTICE_NUM = '819972';


-- STEP 1: CREATE STANDARDIZED LOOKUP VIEW
-- Normalizes all values to uppercase for consistent matching.
CREATE OR REPLACE VIEW MUSA_DAIR_DB.INTERMEDIATE.CITY_PROVINCE_LOOKUP AS
SELECT DISTINCT
    UPPER(TRIM(PROVINCE)) AS PROVINCE,
    NULLIF(UPPER(TRIM(LOCAL_MUNICIPALITY)), '') AS LOCAL_MUNICIPALITY,
    NULLIF(UPPER(TRIM(DISTRICT_MUNICIPALITY)), '') AS DISTRICT_MUNICIPALITY,
    NULLIF(UPPER(TRIM(METROPOLITAN_MUNICIPALITY)), '') AS METROPOLITAN_MUNICIPALITY,
    UPPER(TRIM(CITY)) AS CITY
FROM MUSA_DAIR_DB.RAW.PROVINCE_LOOKUP
WHERE CITY IS NOT NULL 
  AND TRIM(CITY) != '';


-- STEP 2: VERIFY LOOKUP TABLE CONTENTS
-- Confirms the lookup table has expected Gauteng and KZN cities.
SELECT 
    PROVINCE,
    COUNT(DISTINCT CITY) AS CITY_COUNT
FROM MUSA_DAIR_DB.INTERMEDIATE.CITY_PROVINCE_LOOKUP
GROUP BY PROVINCE
ORDER BY PROVINCE;


-- STEP 3: CHECK CURRENT NULL PROVINCE COUNT
-- Baseline count of records missing PROVINCE before matching.
SELECT 
    CASE 
        WHEN PROVINCE IS NULL OR TRIM(PROVINCE) = '' THEN 'MISSING PROVINCE'
        ELSE 'HAS PROVINCE'
    END AS STATUS,
    COUNT(*) AS RECORD_COUNT
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY STATUS;


-- STEP 4: ADD HELPER COLUMN FOR ADDRESS PARSING
-- Extracts the last comma-separated segment from ADDRESS for city matching.
ALTER TABLE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
ADD COLUMN IF NOT EXISTS ADDRESS_LAST_SEGMENT VARCHAR;

UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS_LAST_SEGMENT = UPPER(TRIM(SPLIT_PART(ADDRESS, ',', -1)));


-- STEP 5: ADD HELPER COLUMN FOR SECOND-TO-LAST SEGMENT
-- Some addresses have city in the second-to-last position.
ALTER TABLE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
ADD COLUMN IF NOT EXISTS ADDRESS_SECOND_LAST VARCHAR;

UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS_SECOND_LAST = UPPER(TRIM(
    SPLIT_PART(ADDRESS, ',', GREATEST(ARRAY_SIZE(SPLIT(ADDRESS, ',')) - 1, 1))
));


-- STEP 6: UPDATE PROVINCE USING CITY FIELD (PRIMARY MATCH)
-- Direct match on the CITY column if it exists and PROVINCE is null.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED pc
SET 
    PROVINCE = lookup.PROVINCE,
    LOCAL_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.LOCAL_MUNICIPALITY), ''), lookup.LOCAL_MUNICIPALITY),
    DISTRICT_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.DISTRICT_MUNICIPALITY), ''), lookup.DISTRICT_MUNICIPALITY),
    METROPOLITAN_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.METROPOLITAN_MUNICIPALITY), ''), lookup.METROPOLITAN_MUNICIPALITY)
FROM MUSA_DAIR_DB.INTERMEDIATE.CITY_PROVINCE_LOOKUP lookup
WHERE UPPER(TRIM(pc.CITY)) = lookup.CITY
  AND (pc.PROVINCE IS NULL OR TRIM(pc.PROVINCE) = '');


-- STEP 7: UPDATE PROVINCE USING ADDRESS LAST SEGMENT (SECONDARY MATCH)
-- Matches the last comma-separated segment of ADDRESS against city lookup.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED pc
SET 
    PROVINCE = lookup.PROVINCE,
    LOCAL_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.LOCAL_MUNICIPALITY), ''), lookup.LOCAL_MUNICIPALITY),
    DISTRICT_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.DISTRICT_MUNICIPALITY), ''), lookup.DISTRICT_MUNICIPALITY),
    METROPOLITAN_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.METROPOLITAN_MUNICIPALITY), ''), lookup.METROPOLITAN_MUNICIPALITY)
FROM MUSA_DAIR_DB.INTERMEDIATE.CITY_PROVINCE_LOOKUP lookup
WHERE pc.ADDRESS_LAST_SEGMENT = lookup.CITY
  AND (pc.PROVINCE IS NULL OR TRIM(pc.PROVINCE) = '');


-- STEP 8: UPDATE PROVINCE USING ADDRESS SECOND-TO-LAST SEGMENT (TERTIARY MATCH)
-- Some addresses repeat the city or have extra suffixes.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED pc
SET 
    PROVINCE = lookup.PROVINCE,
    LOCAL_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.LOCAL_MUNICIPALITY), ''), lookup.LOCAL_MUNICIPALITY),
    DISTRICT_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.DISTRICT_MUNICIPALITY), ''), lookup.DISTRICT_MUNICIPALITY),
    METROPOLITAN_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.METROPOLITAN_MUNICIPALITY), ''), lookup.METROPOLITAN_MUNICIPALITY)
FROM MUSA_DAIR_DB.INTERMEDIATE.CITY_PROVINCE_LOOKUP lookup
WHERE pc.ADDRESS_SECOND_LAST = lookup.CITY
  AND (pc.PROVINCE IS NULL OR TRIM(pc.PROVINCE) = '');


-- STEP 9: UPDATE PROVINCE USING CONTAINS MATCH (FALLBACK)
-- Checks if any known city name appears anywhere in the ADDRESS string.
-- Only matches cities with 5+ characters to avoid false positives.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED pc
SET 
    PROVINCE = lookup.PROVINCE,
    LOCAL_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.LOCAL_MUNICIPALITY), ''), lookup.LOCAL_MUNICIPALITY),
    DISTRICT_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.DISTRICT_MUNICIPALITY), ''), lookup.DISTRICT_MUNICIPALITY),
    METROPOLITAN_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.METROPOLITAN_MUNICIPALITY), ''), lookup.METROPOLITAN_MUNICIPALITY)
FROM MUSA_DAIR_DB.INTERMEDIATE.CITY_PROVINCE_LOOKUP lookup
WHERE UPPER(pc.ADDRESS) LIKE '%' || lookup.CITY || '%'
  AND (pc.PROVINCE IS NULL OR TRIM(pc.PROVINCE) = '')
  AND LENGTH(lookup.CITY) >= 5;


-- STEP 10: STANDARDIZE PROVINCE NAMES
-- Ensures consistent casing for province names across all records.
UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PROVINCE = 'Gauteng'
WHERE UPPER(TRIM(PROVINCE)) = 'GAUTENG';

UPDATE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
SET PROVINCE = 'KwaZulu-Natal'
WHERE UPPER(TRIM(PROVINCE)) IN ('KWAZULU-NATAL', 'KWAZULU NATAL', 'KZN');


-- STEP 11: VERIFICATION BEFORE DELETION
-- Checks how many records matched each province and how many remain null.
SELECT 
    CASE 
        WHEN PROVINCE IS NULL OR TRIM(PROVINCE) = '' THEN 'NULL/EMPTY (TO BE DROPPED)'
        ELSE PROVINCE 
    END AS PROVINCE_STATUS,
    COUNT(*) AS RECORD_COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS PERCENTAGE
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY PROVINCE_STATUS
ORDER BY RECORD_COUNT DESC;


-- STEP 12: SAMPLE NULL RECORDS BEFORE DROPPING
-- Reviews a sample of records that will be dropped to verify they are outside GP/KZN.
SELECT 
    PHARMACY_ID,
    PRACTICE_NAME,
    ADDRESS,
    CITY,
    ADDRESS_LAST_SEGMENT,
    ADDRESS_SECOND_LAST
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
WHERE PROVINCE IS NULL OR TRIM(PROVINCE) = ''
ORDER BY RANDOM();


-- STEP 13: DELETE NON-GAUTENG AND NON-KZN RECORDS
-- Removes all records that could not be matched to Gauteng or KwaZulu-Natal.
-- These are pharmacies in other provinces outside the project scope.
DELETE FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
WHERE PROVINCE IS NULL 
   OR TRIM(PROVINCE) = ''
   OR UPPER(TRIM(PROVINCE)) NOT IN ('GAUTENG', 'KWAZULU-NATAL');


-- STEP 14: CLEANUP HELPER COLUMNS
-- Removes the temporary parsing columns used for matching.
ALTER TABLE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
DROP COLUMN IF EXISTS ADDRESS_LAST_SEGMENT;

ALTER TABLE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
DROP COLUMN IF EXISTS ADDRESS_SECOND_LAST;


-- STEP 15: FINAL VERIFICATION
-- Confirms final table contains only Gauteng and KwaZulu-Natal records.
SELECT 
    PROVINCE,
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(DISTINCT PRACTICE_NUM) AS UNIQUE_PRACTICES,
    SUM(CASE WHEN CITY IS NULL OR TRIM(CITY) = '' THEN 1 ELSE 0 END) AS NULL_CITY_COUNT,
    SUM(CASE WHEN COORDS IS NULL THEN 1 ELSE 0 END) AS NULL_COORDS_COUNT
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY PROVINCE
ORDER BY PROVINCE;


-- STEP 16: RECORD COUNTS SUMMARY
-- Final summary of the filtering process.
SELECT 'TOTAL GP/KZN PHARMACIES' AS METRIC, COUNT(*) AS VALUE
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
UNION ALL
SELECT 'GAUTENG COUNT' AS METRIC, COUNT(*) AS VALUE
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
WHERE PROVINCE = 'Gauteng'
UNION ALL
SELECT 'KWAZULU-NATAL COUNT' AS METRIC, COUNT(*) AS VALUE
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
WHERE PROVINCE = 'KwaZulu-Natal'
UNION ALL
SELECT 'NEEDING GEOCODING' AS METRIC, COUNT(*) AS VALUE
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED 
WHERE COORDS IS NULL;
