-- PHARMACIES DEDUPLICATION
-- Creates a deduplicated pharmacies table using PRACTICE_NUM as primary identifier.
-- Records WITH PRACTICE_NUM are deduplicated by grouping on PRACTICE_NUM + PROVINCE.
-- Records WITHOUT PRACTICE_NUM are preserved for later spatial deduplication.
-- Output: MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_DEDUPLICATED.


-- CREATE DEDUPLICATED TABLE
-- Combines deduplication strategy for records with and without PRACTICE_NUM.
CREATE OR REPLACE TABLE MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_DEDUPLICATED AS

-- PART 1: DEDUPLICATED RECORDS WITH PRACTICE_NUM
-- Groups records by PRACTICE_NUM and PROVINCE.
-- Keeps longest PRACTICE_NAME and ADDRESS for best geocoding results.
-- Aggregates all source COMPANY values into comma-separated list.
-- Counts how many networks carry each pharmacy.
SELECT 
    PROVINCE,
    LOCAL_MUNICIPALITY,
    DISTRICT_MUNICIPALITY,
    METROPOLITAN_MUNICIPALITY,
    CITY,
    MAX_BY(PRACTICE_NAME, LENGTH(PRACTICE_NAME)) AS PRACTICE_NAME,
    PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    MAX_BY(ADDRESS, LENGTH(ADDRESS)) AS ADDRESS,
    MAX(PHONE) AS PHONE,
    'Private' AS FUNDING,
    LISTAGG(DISTINCT COMPANY, ', ') WITHIN GROUP (ORDER BY COMPANY) AS COMPANIES,
    COUNT(DISTINCT COMPANY) AS NETWORK_COUNT,
    NULL AS COORDS
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
WHERE PRACTICE_NUM IS NOT NULL
GROUP BY PRACTICE_NUM, PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY

UNION ALL

-- PART 2: KEEP ALL RECORDS WITHOUT PRACTICE_NUM
-- Preserves all records lacking PRACTICE_NUM for spatial deduplication later.
-- These records will be deduplicated post-geocoding using coordinate proximity.
SELECT 
    PROVINCE,
    LOCAL_MUNICIPALITY,
    DISTRICT_MUNICIPALITY,
    METROPOLITAN_MUNICIPALITY,
    CITY,
    PRACTICE_NAME,
    NULL AS PRACTICE_NUM,
    PRACTICE_TYPE,
    ADDRESS,
    PHONE,
    FUNDING,
    COMPANY AS COMPANIES,
    1 AS NETWORK_COUNT,
    COORDS
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_COMBINED
WHERE PRACTICE_NUM IS NULL;


-- VALIDATION: RECORD COUNTS BY PRACTICE_NUM STATUS
-- Verifies the deduplication results.
SELECT 'DEDUPLICATED RECORD COUNTS' AS VALIDATION;
SELECT 
    CASE WHEN PRACTICE_NUM IS NOT NULL THEN 'Has PRACTICE_NUM' ELSE 'NULL PRACTICE_NUM' END AS PRACTICE_NUM_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_DEDUPLICATED
GROUP BY PRACTICE_NUM_STATUS;


-- VALIDATION: NETWORK COUNT DISTRIBUTION
-- Shows how many pharmacies are on multiple networks.
SELECT 'NETWORK COUNT DISTRIBUTION' AS VALIDATION;
SELECT 
    NETWORK_COUNT,
    COUNT(*) AS PHARMACY_COUNT
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_DEDUPLICATED
WHERE PRACTICE_NUM IS NOT NULL
GROUP BY NETWORK_COUNT
ORDER BY NETWORK_COUNT;


-- VALIDATION: TOTAL RECORD COUNT
-- Total records after deduplication.
SELECT 'TOTAL DEDUPLICATED RECORDS' AS VALIDATION;
SELECT COUNT(*) AS TOTAL_RECORDS 
FROM MUSA_DAIR_DB.INTERMEDIATE.PHARMACIES_DEDUPLICATED;
